import { InMemoryDbService } from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const heroes = [
      {id:1,
      name: 'The Time Machine',
      author: 'H.G.Wells',
      isbn: 101,
      publicationdate: '1-1-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Science Fiction',
      format: 'Pdf'
    },
      {id:2,
      name: 'The War of Worlds',
      author: 'H.G.Wells',
      isbn: 102,
      publicationdate: '1-1-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Science Fiction',
      format: 'Pdf' },

      {id:3,
      name: 'Snow Crash',
      author: 'Neal Stephenson',
      isbn: 103,
      publicationdate: '1-2-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Science Fiction',
      format: 'Pdf' },

      {id:4,
      name: 'The Diamond Age',
      author: 'Neal Stephenson',
      isbn: 104,
      publicationdate: '1-2-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Science Fiction',
      format: 'Pdf' },

      {id:5,
      name: 'The Alchemist',
      author: 'Paulo Coelho',
      isbn: 105,
      publicationdate: '1-3-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Fiction',
      format: 'Pdf' },

      {id:6,
      name: 'Eleven Minutes',
      author: 'Paulo Coelho',
      isbn: 106,
      publicationdate: '1-3-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Fiction',
      format: 'Pdf' },

      {id:7,
      name: 'The Origin',
      author: 'Dan Brown',
      isbn: 107,
      publicationdate: '1-4-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Fiction',
      format: 'Pdf' },

      {id:8,
      name: 'The Da Vinci Code',
      author: 'Dan Brown',
      isbn: 108,
      publicationdate: '1-4-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Fiction',
      format: 'Pdf' },

      {id:9,
      name: 'The Notebook',
      author: 'Nicholas Sparks',
      isbn: 109,
      publicationdate: '1-5-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Romance',
      format: 'Pdf' },

      {id:10,
      name: 'A Walk to Remember',
      author: 'Nicholas Sparks',
      isbn: 110,
      publicationdate: '1-5-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Romance',
      format: 'Pdf' },

      {id:11,
      name: 'The Fault in Our Stars',
      author: 'John Green',
      isbn: 111,
      publicationdate: '1-6-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Romance',
      format: 'Pdf' },

      {id:12,
      name: 'Let It Snow',
      author: 'John Green',
      isbn: 112,
      publicationdate: '1-6-2017',
      publisher: 'Phoenix Publishers',
      price: 300,
      genre:'Romance',
      format: 'Pdf' }

    ];
    return {heroes};
  }
}
